export default {
  products: [
    {
      _id: '1',
      name: 'Full Aqua SiteWeb',
      category: 'Site',
      image: '/images/product-1.jpg',
      brand: 'Aqua',
      price: 400,
      countInStock:6,
    },
    {
      _id: '2',
      name: 'Full Aquaview SiteWeb',
      category: 'Site',
      image: '/images/product-2.jpg',
      price: 400,
      brand: 'Aquaview',
      countInStock:6,
    },
    {
      _id: '3',
      name: 'Full Ocean SiteWeb',
      category: 'Site',
      image: '/images/product-3.jpg',
      price: 400,
      brand: 'Ocean',
      countInStock:6,
    },
    {
      _id: '4',
      name: "Full Interface SiteWeb",
      category: 'Site',
      image: '/images/product-4.jpg',
      price: 400,
      brand: "Interface",
      countInStock:6,
    },
    {
      _id: '5',
      name: 'Full Pyramides SiteWeb',
      category: 'Site',
      image: '/images/product-5.jpg',
      price: 400,
      brand: 'Pyramides',
      countInStock:6,
    },
    {
      _id: '6',
      name: 'Full Pyramide SiteWeb',
      category: 'Site',
      image: '/images/product-6.png',
      price: 400,
      brand: 'Pyramide',
      countInStock:6,
    },
  ],
};
